---
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: ./.env.ci
    environment:
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    depends_on:
      - db
    command: npm test

  db:
    env_file: ./.env.ci
    image: postgres:12.3-alpine
    volumes:
      - devops-lvl1-pg-volume:/var/lib/postgresql/data

volumes:
  devops-lvl1-pg-volume:
